# configs/f.yaml
# Stage F: EMNIST + pretrained conv1 filters
dataset: emnist
seeds: [42, 43, 44]

analyze:
  sample_ratio: 0.1
  every_n_epochs: 1

model:
  conv1_channels: 55
  pretrained_filter_path: "/home/tonyhuh/again_0716/filters_emnist_pct5_k55_9_pruned_corr80.npy"
  embed_dim: 32
  num_heads: 4
  num_classes: 47
  conv2_dropout: 0.1
  conv2corr_lambda: 0.1

  num_experts: 3
  expert_hidden: 128
  top_k: 3

  gating:
    type: both
    lambda_load: 0.003
    lambda_ent: 0.0003

  ohem:
    use_ohem: True
    keep_ratio: 0.6

opt:
  lr: 1e-3
  epochs: 20
  batch_size: 128

augment:
  strength: custom
  presets:
    custom: [randaugment]
  params:
    randaugment:
      num_ops: 20
      magnitude: 9
